# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidebar_name', models.CharField(default='SS1', max_length=50)),
                ('tittle', models.CharField(default='Shadowsocket', max_length=50)),
                ('descript', models.TextField()),
                ('server', models.CharField(default='127.0.0.1', max_length=50)),
                ('server_port', models.CharField(default='1117', max_length=50)),
                ('password', models.CharField(default='*******', max_length=50)),
                ('method', models.CharField(default='rc4-md5', max_length=50)),
                ('qr_type', models.CharField(default='ss', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NavBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='nav1', max_length=50)),
                ('tittle', models.CharField(default='tittle', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='item1_name', max_length=50)),
                ('tittle', models.CharField(default='item1_tittle', max_length=50)),
                ('navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.NavBar')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='sidebar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SideBar'),
        ),
    ]
